### ISSUE TITLE
Support contextual settings

### ISSUE THREAD

**Issue by FroMage** [smallrye/smallrye-context-propagation#198]
ATM we specify settings for which contexts get propagated when creating a `ThreadContext` or `ManagedExecutor` and then, all manual wrapping of lambdas is done via those objects who use those settings:

```java
@GET
public CompletionStage<String> hello(){
 ThreadContext ctx = ThreadContext.builder()
                                    .propagated(ThreadContext.ALL)
                                    .build();
 CompletableFuture<Something> cf = api.getSomething();
 return ctx.withContextCapture(cf).thenApply(something -> {
    // I have all contexts here
    return "OK";
 });
}
```

Libraries like Munity on the other hand provide support for CP by having a single `ThreadContext` object they use to wrap all the lambdas and so the default (and most useful) setting is to propagate every context, which is what we almost always want from REST endpoints as we do most commonly in Quarkus:

```java
@GET
public Uni<String> hello(){
 Uni<Something> cf = api.getSomething();
 return cf.map(something -> {
    // I have all contexts here
    return "OK";
 });
}
```

Now, for some use-cases we may want to be able to disable CP, or alter which contexts are propagated, in Mutiny.

We could treat this as a Mutiny issue, and solve it with an API that looks like this:

```java
@GET
public Uni<String> hello(){
 Uni<Something> cf = api.getSomething().noContext();
 return cf.map(something -> {
    // I have no context here
    return "OK";
 });
}
```

This would disable context propagation for all dependent stages, but:

- not for any of the stages created by `api.getSomething()`
    - We could actually retro-actively apply this if we keep back-references and lazily wrap the lambdas so that at the time we disable CP we haven't wrapped them yet, but this retro-active stuff seems dodgy
- would introduce a CP dependency in Mutiny core, rather than install it via a plugin
    - Now, perhaps that's not that bad, because it can depend on the MP definition, and the visible API would be only enable/disable (boolean) or specify which contexts (they're `String` names).

An alternative could be to make the context propagation contextual, like we do for `@Transactional` via a CDI interceptor:

```java
@WithContexts({}) // no contexts
@GET
public Uni<String> hello(){
 Uni<Something> cf = api.getSomething(); // even this call would not have contexts
 return cf.map(something -> {
    // I have no context here
    return "OK";
 });
}
```

But this would require a `ThreadLocal<ThreadContext>` which, guess what, we'd probably have to propagate (and we've gone full circle), like in the following example:

```java
@WithContexts({}) // no contexts
@GET
public Uni<String> hello(){
 Uni<Something> cf = api.getSomething(); // even this call would not have contexts
 return cf.flatMap(something -> {
    // I have no context here, but let's suppose I'm in a new async thread, so I still expect that this will have
    // no context
    return api.getSomething().map(s2 -> {
      // at this point, visually it looks like I should have no context, right?
      // so I do need to propagate the `ThreadContext` TL
      return "OK";
    });
 });
}
```

Setting aside the fact that disabling CP should or should not disable propagation of the `ThreadContext` (that's a hairy one), this would work.

Another alternative is to make it an explicitely scope-based (non-propagated) thing, orthogonal to CP:

```java
@GET
public Uni<String> hello(){
 try(FuckingUselessType ignoreMe = ThreadContext.noPropagation()) {
   Uni<Something> cf = api.getSomething(); // even this call would not have contexts
   return cf.flatMap(something -> {
      // I have no context here, but let's suppose I'm in a new async thread, so to make sure I have no context
      // I need to redo another try/resource:
      try(FuckingUselessType ignoreMe2 = ThreadContext.noPropagation()) {
        return api.getSomething().map(s2 -> {
          // at this point, I have no context either
          return "OK";
        });
      }
     });
  }
}
```

This is much easier to implement, it's purely scope-based, but not propagated, which means it's a death-trap in reactive programming because you never know which thread is calling you.

Note that I've created this in SR-CP, but it could end up being an issue in Munity, or we could even go up to the MP-CP spec to see if perhaps OpenLiberty has a solution for this.

@kabir @cescoffier @kenfinnigan

**Comment by FroMage** [comment]
Actually, we could support the last scope-based solution API, and declare that the `ThreadContext` in question, when used, will propagate itself. That's a variant of both solutions, and lets us do:
```java
@GET
public Uni<String> hello(){
 try(FuckingUselessType ignoreMe = ThreadContext.noPropagation()) {
   Uni<Something> cf = api.getSomething(); // even this call would not have contexts
   return cf.flatMap(something -> {
      // I have no context here, but the ThreadContext propagated itself, 
      // so even if I'm in a new async thread, I will keep on having no context
      return api.getSomething().map(s2 -> {
        // at this point, I have no context either
        return "OK";
      });
     });
  }
}
```

And of course, we can implement `@WithContext` with this API, so this would work too:

```java
@WithContexts({}) // no contexts
@GET
public Uni<String> hello(){
 Uni<Something> cf = api.getSomething(); // even this call would not have contexts
 return cf.flatMap(something -> {
    // I have no context here, but let's suppose I'm in a new async thread, so I still expect that this will have
    // no context
    return api.getSomething().map(s2 -> {
      // no context either, besides the ThreadContext in scope
      return "OK";
    });
 });
}
```

**Comment by FroMage** [comment]
Note that even I bring this to the spec, we won't be able to use it until we make a release, which is not possible ATM, so we'll need a SR-CP equivalent until then.

**Comment by FroMage** [comment]
@kabir this should be trivial to test, but how fast can you confirm if it works for you if I push a SR-CP release out with it?

**Comment by FroMage** [comment]
Forgot to mention @manovotn for opinions.

**Comment by kabir** [comment]
Does this cover the 'opposite' use-case?

e.g. say I have the following reactive messaging methods

```java
@Incoming("source")
@Outgoing("sink")
public PublisherBuilder<String> process(PublisherBuilder<String> pb) {
   return pb.map(v -> .....);
}
```

So before the process method is called (as part of reactive messaging) we will/should not have context propagation on the PublisherBuilder.
I then do something in my method (I guess by adding `@WithContexts(ALL)`, `ThreadContext.withPropagation` or something like that) to turn on CP so that my `pb.map()` can benefit.
Once my method returns and reactive messaging 'owns' it again it should not have CP.

Generally I can test very quickly, like in an hour. But right now we're looking at early next week. I don't need a SmallRye context propagation release, just let me know a branch with your WIP and I can build it myself and try it out.

**Comment by FroMage** [comment]
OK thanks.

Well, I'll need to know what contexts are active when you call `process`? CDI (request?)? Transaction? other?

As to what happens to the parameters passed to the method, I can't do that in a CDI interceptor: the parameters are invoked after the parameter list is built, so I think it will be dependent on how reactive-messaging builds these parameters. Question for @cescoffier I guess.

**Comment by kabir** [comment]
As discussed with @FroMage on chat, there shouldn't really be any context propagation for the `process()` method as there is no user request to use @RequestScoped beans from so no CDI is needed. Also, there can not be any user initiated transaction so we should not propagate that.

But I now wonder if we might need to propagate the TCCL for the `pb` calls in the `process()` method? In WildFly I am using the "Application" context for that.

**Comment by cescoffier** [comment]
Reactive Messaging does not use method interceptors. The streams are either coming from connectors or from the user. However, in both cases, the creation is done before the application starts. So, I'm not sure which context you see.

**Comment by FroMage** [comment]
This is done.
