### ISSUE TITLE
Cleaning up ContextManagers

### ISSUE THREAD

**Issue by kabir** [smallrye/smallrye-context-propagation#216]
I'm looking for some hooks in SmallRyeContextManagerProvider since the spec API doesn't really lend itself to what I need to do to clean up on undeployment. Essentially the following lazily initialises and registers a ContextManager as the code in my deployment uses it
```
    @Override
    public SmallRyeContextManager getContextManager() {
        return getContextManager(Thread.currentThread().getContextClassLoader());
    }

    @Override
    public SmallRyeContextManager getContextManager(ClassLoader classLoader) {
        // Registers the manager for the classloader if it cannot be found
    }
```
That part is fine. I don't want to have my deployers create a context manager as I have no way of knowing if deployments need it.

The problem is the unregister() method which takes a ContextManager instance to unregister
```
    public void releaseContextManager(ContextManager manager) {
        // Remove the manger
    }
```
I need to call this on undeployment, but as I don't know which managers exist, the only option at the moment is to call `getContextManager(classLoader)` with the deployment classloader. However, this will register a ContextManager for the class loader if one does not exist, which is pointless since my next step is to remove it :)

Do any of the following changes to SmallRyeContextManagerProvider work for you?

1) Add something like a `findContextManager(ClassLoader cl)` method. It would work more or less the same as the `getContextManager(ClassLoader cl)` method but not create a ContextManager if not found.

2) Add a `releaseContextManager(ClassLoader cl)` method. It would remove from the `contextManagersForClassLoader` map directly without the iteration that happens in the current variant.

3) Make the constructor protected rather than the current package protected visibility. I can then subclass SmallRyeContextManagerProvider in WildFly and intercept the `getContextManager(ClassLoader classLoader)` calls and maintain my own map of ClassLoader -> ContextManager mappings so I have the necessary information to clean up on undeployment.

@FroMage If you let me know which of these you prefer (or have better ideas) I am happy to open a PR with the changes

**Comment by manovotn** [comment]
I'd say option 1 is nice since it gives you the general capability of looking for any manager based on CL (for other possible use cases). Alternatively, you could go with something like `releaseContextManagerIfExists(ClassLoader cl)` which would only do it if there is one, otherwise it would silently pass (since I suppose you don't want to blow up if there is none).

**Comment by FroMage** [comment]
Option 1 looks fine to me, or add an optional `boolean create` parameter to `getContextManager`. Whatever :)
