### ISSUE TITLE
Asynchronous execution of `ManagedExecutor` not working as expected

### ISSUE THREAD

**Issue by schoeffm** [smallrye/smallrye-context-propagation#227]
Hi all,

sorry for the vage title but I'm not sure if there's sth. wrong in my setup or an actual misbehavior.

I'm trying to create a REST-Resource which triggers an asynchronous task that runs in the background - the caller though, should get a immediate response stating that the respective task was triggered.

I did this with stock Quarkus (just added the smallrye context-propagation extension) as you can check in [this showcase-repo](https://github.com/schoeffm/executor-demo) - it basically only contains two classes:

```java
...
        logger.info("\n- Processor-Count: {}" +
                    "\n- ForkJoinPool Parallelism: {}",
                Runtime.getRuntime().availableProcessors(),
                ForkJoinPool.commonPool().getParallelism());

        logger.info(Thread.currentThread().getName());
        executor.newIncompleteFuture()
                .supplyAsync(() -> Thread.currentThread().getName())
                .thenApply(name -> { sleep(5000L); return name; })
                .thenAccept(name -> logger.info("Finished async processing: {}", name));

        logger.info("Delivering REST-Response");

        return "triggered";
...
```
while the provider-code for the `ManagedExecutor`-instance looks like this:
```java
    @Produces
    @ApplicationScoped
    @MyExecutor
    ManagedExecutor executor = ManagedExecutor.builder()
            .propagated(ThreadContext.TRANSACTION)
                .maxAsync(10)
                .maxQueued(25)
                .build();

    void disposeExecutor(@Disposes @MyExecutor ManagedExecutor exec) {
        exec.shutdownNow();
    }

    @Qualifier
    @Retention(RetentionPolicy.RUNTIME)
    @Target({ ElementType.FIELD, ElementType.METHOD, ElementType.PARAMETER })
    public @interface MyExecutor {}
```

When I start that application - the first request takes ~5 sec. to complete while the asynchronous task seems to be executed in the http-handling thread (in case of Quarkus `executor-thread-1`). For the subsequent request it depends ... sometimes it also takes ~5sec sometimes not. At some point it seems the system picked up the executor and uses threads from `ForkJoinPool.commonPool` to do the async stuff. 

A typical log-output looks like this:
```
2020-10-27 10:52:38,544 INFO  [jav.lan.Exception] (executor-thread-1)
- Processor-Count: 4
- ForkJoinPool Parallelism: 3
2020-10-27 10:52:38,547 INFO  [jav.lan.Exception] (executor-thread-1) executor-thread-1
2020-10-27 10:52:43,525 INFO  [jav.lan.Exception] (executor-thread-1) Finished async processing: ForkJoinPool.commonPool-worker-3
2020-10-27 10:52:43,526 INFO  [jav.lan.Exception] (executor-thread-1) Delivering REST-Response
2020-10-27 10:54:41,000 INFO  [jav.lan.Exception] (executor-thread-1)
- Processor-Count: 4
- ForkJoinPool Parallelism: 3
2020-10-27 10:54:41,000 INFO  [jav.lan.Exception] (executor-thread-1) executor-thread-1
2020-10-27 10:54:45,967 INFO  [jav.lan.Exception] (executor-thread-1) Finished async processing: ForkJoinPool.commonPool-worker-3
2020-10-27 10:54:45,968 INFO  [jav.lan.Exception] (executor-thread-1) Delivering REST-Response
2020-10-27 10:54:49,394 INFO  [jav.lan.Exception] (executor-thread-1)
- Processor-Count: 4
- ForkJoinPool Parallelism: 3
2020-10-27 10:54:49,394 INFO  [jav.lan.Exception] (executor-thread-1) executor-thread-1
2020-10-27 10:54:49,395 INFO  [jav.lan.Exception] (executor-thread-1) Delivering REST-Response
2020-10-27 10:54:54,396 INFO  [jav.lan.Exception] (ForkJoinPool.commonPool-worker-3) Finished async processing: ForkJoinPool.commonPool-worker-3
```
where only the third execution behaves as expected - Delivering REST-Response _before_ finishing the async task.

I did an asciinema since it's difficult to describe - so you don't necessarily have to look at my [showcase](https://github.com/schoeffm/executor-demo)
[![asciicast](https://asciinema.org/a/EakG6g6dut6y1LEnpqJ05EQ91.svg)](https://asciinema.org/a/EakG6g6dut6y1LEnpqJ05EQ91)

I also added a [branch to the showcase-repo](https://github.com/schoeffm/executor-demo/tree/payara) where I tried that showcase with payara (adding the necessary dependencies manually) ... but the result is the same.

Can you plz have a look what's goin' on there ... is it my setup which is wrong or is this a known thing? If so, how can I enforce the usage of the thread-pool in all cases?

Thx in advance

**Comment by FroMage** [comment]
Hi.

When you call `cf.supplyAsync` it will queue the method in a fork-join pool. But then your main thread calls `thenAccept` which will have two behaviours depending on whether the original stage is finished or not: if `supplyAsync` was fast enough that it's already done, the function (`sleep`) is called in the current thread, which does block your response. If not, it is queued on the stage that will run in the fork-join pool, and will be executed by that same pool.

So that explains why your method sometimes blocks (if the `supplyAsync` is fast enough), and sometimes doesn't.

This looks to me to be a `CompletableFuture` usage question rather than a bug in SR-CP, no?

Hope that helps. Let me know if you have further questions, otherwise could you please close this issue?

**Comment by schoeffm** [comment]
Although I have to give that answer a bit more time to sink it is absolutely right. As soon as I make the `supplyAsync` call slow enough the behaviour is predictable ... leading to the conclusion that I indeed have to look closer on the usage of `CompletableFuture` just as you wrote.
Thx for the hint ...
