### ISSUE TITLE
Align impl with spec name change

### ISSUE THREAD

**Issue by manovotn** [smallrye/smallrye-context-propagation#43]
Spec was renamed to MP Context Propagation therefore impl needs to consume new artifacts.
After that, I suppose we are changing SmallRye Concurrency to SmallRye Context Propagation, am I right, @kenfinnigan?

We should solve all other hanging issues and PRs prior to project rename as there will be massive clashes otherwise.

**Comment by kenfinnigan** [comment]
+1 @manovotn

I've avoided renaming so far as I knew PRs would be a nightmare

**Comment by FroMage** [comment]
@manovotn I'll update the code to align with the spec package changes.

**Comment by FroMage** [comment]
Just renamed everything, will rename this project too, but not sure how to rename the CI project.

**Comment by FroMage** [comment]
project renamed

**Comment by kenfinnigan** [comment]
CI renamed

**Comment by FroMage** [comment]
Thanks a lot. I can close this then :)
