### ISSUE TITLE
Latest release is not compatible with Java 11

### ISSUE THREAD

**Issue by jponge** [smallrye/smallrye-context-propagation#456]
The upgrade from 2.1.0 to 2.1.1 shows a breaking change wrt class files version: https://github.com/smallrye/smallrye-mutiny/pull/1618

/cc @FroMage

**Comment by FroMage** [comment]
Ah, it had to be compatible with Java 11? The build was previously done on Java 17 though, I thought I had just confirmed what was already the case. Damnit.

Well, I suppose I'll add Java 11 on the test list then.

**Comment by jponge** [comment]
TBH we should bump to 17 in Mutiny at some point, too

**Comment by FroMage** [comment]
I'll hold back on releasing a new version because I'm not sure I need other fixes for https://github.com/quarkusio/quarkus/pull/41064

**Comment by jponge** [comment]
We're getting failing tests now :-) https://github.com/smallrye/smallrye-mutiny/actions/runs/9462772708/job/26067209491?pr=1621

**Comment by FroMage** [comment]
Yeah, we had a similar one in Quarkus, and @cescoffier said it's fine to update the tests :)

```
Expecting message to be:
  "Failed"
but was:
  "java.lang.RuntimeException: Failed"
```

**Comment by jponge** [comment]
Great, I have a plan now 🤣
